name: .NET

on:
  push:
    branches:
      - feature/*
      - develop
      - master
  pull_request:
    branches:
      - develop
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET Core SDKs
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            3.0.x
            3.1.x
            5.0.x
            6.0.x
            7.0.x
            8.0.x
            9.0.x
      - run: dotnet --list-sdks
      - run: dotnet restore ./Examples/Tests/Tests.csproj
      - run: dotnet test ./Examples/Tests/Tests.csproj --verbosity normal
