name: .NET

on:
  push:
    branches: [develop, master]
  pull_request:
    branches: [develop, master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"
      - run: dotnet restore ./Examples/Tests/Tests.csproj
      - run: dotnet test ./Examples/Tests/Tests.csproj --verbosity normal
