name: .NET

on:
  push:
    branches: [develop, master]
  pull_request:
    branches: [develop, master]

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dotnet-version: ["3.1.x", "5.0.x", "6.0.x", "7.0.x", "8.0.x", "9.0.x"]

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - run: dotnet restore ./Examples/Tests/Tests.csproj
      - run: dotnet test ./Examples/Tests/Tests.csproj --verbosity normal
